### ISSUE TITLE
Node not saving

### ISSUE THREAD

**Issue by SanderVanCamp** [front/drupal-gutenberg#1]
When trying to save a node, the page does nothing. Only logs some json in the console. I can't find where this problem is coming from. Not even custom submit handlers are executed. If I would know, I would be happy to solve this.

**Comment by perandre** [comment]
Thanks for getting in touch, @SanderVanCamp. We're on vacation, but I'll make sure @vonloxx gets back to you when he is back. A lot of exciting things going on!

**Comment by SanderVanCamp** [comment]
@perandre Thank you! Looking forward to it!

**Comment by vonloxx** [comment]
@SanderVanCamp I just updated the 8.x-1.x branch with the latest development. Please check that branch. Eventually this repository will be turned off in favor of drupal.org repository. We're just waiting for the namespace to be available 😉.

**Comment by jmolivas** [comment]
@vonloxx  I tried syncing to latest commit and also the one on do (sandbox project) but not sure why I am not getting a functional editor seems more like assets (js/css) are not loading properly, therefore, node is still not saving.

**Comment by stevector** [comment]
I think I experienced the same problem as @SanderVanCamp and I found that I had not entered a node title.

When I entered a title in the sidebar I was able to save the node.

<img width="1429" alt="screen shot 2018-08-06 at 12 36 09 pm" src="https://user-images.githubusercontent.com/211029/43731821-5ae75fec-9975-11e8-8c81-c5097c6c1f3b.png">

**Comment by jmolivas** [comment]
@stevector My screen does not like that even save/preview/delete buttons are not located properly.

Are you using a particular theme or make any theme customizations?

Did you customize the form display?

**Comment by stevector** [comment]
@jmolivas I think all I did was enable the module (8.x-1.x branch) and click this checkbox:

<img width="1105" alt="screen shot 2018-08-06 at 8 44 31 am" src="https://user-images.githubusercontent.com/211029/43743144-489a72fa-999a-11e8-8e1d-bd03a4f22ad9.png">

**Comment by jmolivas** [comment]
Awesome @stevector that was the issue ;)
