### ISSUE TITLE
How to write new block?

### ISSUE THREAD

**Issue by hoainam12k** [front/drupal-gutenberg#7]
Hello, do you have any guide to create new custom block for gutenberg editor? Or any starter module? I want to write some custom block but don't know where to start yet.

**Comment by perandre** [comment]
Hi, thanks for your interest!

While it is quite straight forward, we haven't finished the setup for managing custom blocks. It will be released in a couple of weeks. That said, we do have some docs we will post later today, so I'll leave the issue open.

**Comment by hoainam12k** [comment]
that's great, waiting for it :)

**Comment by SofiaSousa** [comment]
Hey @hoainam12k!

We're working on the documentation right now. 

We already have an example block that can help you. Here it is: https://github.com/front/g-hero-section, you can check how to create and register a block in your Gutenberg editor. Hope it helps you!

**Comment by perandre** [comment]
Hi, I thought I saw my collegue post here, but I was wrong. 

Two resources to check out: 

1. https://github.com/front/gutenberg-js#custom-blocks
2. Some quick scaffolding as done in WP: https://github.com/ahmadawais/create-guten-block(but strip away the WP stuff)

However, our solution for actually using the blocks are not ready. The process will eventually be that you just drop a folder inside the module folder, and it should load automatically.
